environment:
  nodejs_version: "18"

branches:
  only:
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: 
  mode: Script
  script:
    - npm install
    - npm run build

test_script:
  - npm run lint && npm test  # скрипт тестирования
